version: '2'
services:
    tatami-cassandra:
        container_name: tatami-cassandra
        build:
            context: .
            dockerfile: cassandra/Cassandra-Dev.Dockerfile
        # volumes:
        #     - ~/volumes/jhipster/tatami/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    tatami-cassandra-node:
        build:
            context: .
            dockerfile: cassandra/Cassandra-Dev.Dockerfile
        links:
            - tatami-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
